### ISSUE TITLE
TypeError: Cannot read property 'cacheable' of undefined

### ISSUE THREAD

**Issue by kafeltz** [jahredhope/base64-image-loader#5]
I look at the source and I see a undeclared property this.cacheable()

where is it declared? It's a mixing?

How does the test works?

**Comment by jahredhope** [comment]
Cacheable informs Webpack that if the loader gets the same request with the same parameters it will return the same result, this is helpful for performance as the first result can be used for later results.

If your getting an error possibly it is due to a newer version of Webpack 2 that I haven't checked yet, if so I can have a look if you give me the version. Thanks.

I can't find a link in the new documentation, but according to the documentation for Webpack 1:
```
flag itself cacheable if possible
Most loaders are cacheable, so they should flag itself as cacheable.

Just call cacheable in the loader.

// Cacheable identity loader
module.exports = function(source) {
    this.cacheable();
    return source;
};
```
https://webpack.github.io/docs/how-to-write-a-loader.html
